import { ValidationRule } from "./ValidationRule.js";
import { ValidationEngine } from "./ValidationEngine.js";
import { indexToCol } from "../../utils/cellRef.js";
import type { ColumnTypeManager } from "../../workbook/managers/ColumnTypeManager.js";

const AUTO_RULE_PRIORITY = 1000;
const BRIDGE_SOURCE = "column-validation";

/**
 * 列类型-验证桥接器
 *
 * 将 ColumnConfig.validation 子对象自动同步到 DataValidationPlugin 的 ValidationEngine，
 * 消除双重验证，统一验证入口。
 *
 * 核心职责：
 * - 从 columns[].validation 创建 ValidationRule（直传模式）
 * - 向后兼容：从 type+options 推断 ValidationRule（推断模式）
 * - 增量同步：配置未变时跳过
 * - 手动规则优先：pluginOptions.rules 优先级高于自动规则
 * - 桥接器驱动降级：通过 markBridgeTaken/unmarkBridgeTaken 控制列类型验证降级
 */
export class ColumnTypeValidationBridge {
    #active: boolean = false;
    #columnTypeManager: ColumnTypeManager;
    #validationEngine: ValidationEngine;

    /** 自动规则 ID → 列号 */
    #autoRuleToColumn: Map<string, number> = new Map();

    /** 列号 → 自动规则 ID */
    #columnToAutoRule: Map<number, string> = new Map();

    /** 列号 → 上次同步的 validation 快照（增量同步用） */
    #lastSyncedValidation: Map<number, Record<string, any>> = new Map();

    /** 自动规则默认 errorStyle */
    #defaultErrorStyle: string = "stop";

    /** 手动规则优先 */
    #respectManualRules: boolean = true;

    constructor(
        columnTypeManager: ColumnTypeManager,
        validationEngine: ValidationEngine,
        options: {
            defaultErrorStyle?: string;
            respectManualRules?: boolean;
        } = {},
    ) {
        this.#columnTypeManager = columnTypeManager;
        this.#validationEngine = validationEngine;
        if (options.defaultErrorStyle) this.#defaultErrorStyle = options.defaultErrorStyle;
        if (options.respectManualRules !== undefined) this.#respectManualRules = options.respectManualRules;
    }

    get active(): boolean {
        return this.#active;
    }

    /**
     * 激活桥接器并全量同步
     */
    activate(): void {
        this.#active = true;
        this.syncFromColumnConfig();
    }

    /**
     * 停用桥接器（清除所有自动规则 + 接管标记）
     */
    deactivate(): void {
        this.clearAutoGeneratedRules();
        this.#columnTypeManager.clearBridgeTaken();
        this.#active = false;
    }

    /**
     * 清除所有自动生成的验证规则
     */
    clearAutoGeneratedRules(): void {
        for (const ruleId of this.#autoRuleToColumn.keys()) {
            this.#validationEngine.removeRule(ruleId);
        }
        this.#autoRuleToColumn.clear();
        this.#columnToAutoRule.clear();
        this.#lastSyncedValidation.clear();
    }

    /**
     * 销毁桥接器
     */
    destroy(): void {
        this.deactivate();
        (this.#columnTypeManager as any) = null;
        (this.#validationEngine as any) = null;
    }

    /**
     * 从列配置全量同步验证规则
     *
     * 遍历所有列配置：
     * - 有 validation 的列 → 从 validation 子对象创建规则
     * - 无 validation 但有可桥接约束的列 → 从 type+options 推断规则（向后兼容）
     * - 无约束的列 → 跳过
     */
    syncFromColumnConfig(): void {
        if (!this.#active) return;

        const columnsConfig = this.#columnTypeManager.columnsConfig;

        for (const [col] of columnsConfig) {
            this.syncColumn(col);
        }

        for (const [col] of this.#columnToAutoRule) {
            if (!columnsConfig.has(col)) {
                this.#removeAutoRuleForColumn(col);
            }
        }
    }

    /**
     * 同步单列配置变更
     *
     * 优先级：
     * 1. validation 子对象存在 → 直传模式
     * 2. validation 不存在 + 有可桥接约束 → 推断模式（向后兼容）
     * 3. 无约束 → 移除已有自动规则
     */
    syncColumn(col: number): void {
        if (!this.#active) return;

        const config = this.#columnTypeManager.getColumnConfig(col);
        const currentSnapshot = config ? this.#extractValidationSnapshot(config) : null;
        const lastSnapshot = this.#lastSyncedValidation.get(col) || null;

        if (this.#snapshotEqual(currentSnapshot, lastSnapshot)) return;

        this.#removeAutoRuleForColumn(col);

        if (config) {
            let rule: ValidationRule | null = null;

            if (config.validation) {
                rule = this.#createRuleFromValidation(col, config);
            } else if (this.#hasBridgeableConstraint(config)) {
                rule = this.#createRuleFromColumnType(col, config);
            }

            if (rule) {
                if (this.#respectManualRules && this.#hasManualRuleForColumn(col, rule.type)) {
                    this.#columnTypeManager.markBridgeTaken(col);
                    this.#lastSyncedValidation.set(col, currentSnapshot!);
                    return;
                }

                const ruleId = this.#validationEngine.addRule(rule);
                this.#autoRuleToColumn.set(ruleId, col);
                this.#columnToAutoRule.set(col, ruleId);

                this.#columnTypeManager.markBridgeTaken(col);
            } else {
                this.#columnTypeManager.unmarkBridgeTaken(col);
            }
        } else {
            this.#columnTypeManager.unmarkBridgeTaken(col);
        }

        this.#lastSyncedValidation.set(col, currentSnapshot || {});
    }

    /**
     * 手动规则移除后的回补
     */
    onManualRuleRemoved(col: number, validationType: string): void {
        if (!this.#active) return;
        const config = this.#columnTypeManager.getColumnConfig(col);
        if (!config) return;

        if (config.validation) {
            const inferredType = config.validation.type || this.#inferValidationType(config.type as string, config);
            if (inferredType !== validationType) return;
        } else if (!this.#hasBridgeableConstraint(config)) {
            return;
        }

        if (this.#hasManualRuleForColumn(col, validationType)) return;

        const rule = config.validation ? this.#createRuleFromValidation(col, config) : this.#createRuleFromColumnType(col, config);

        if (rule) {
            const ruleId = this.#validationEngine.addRule(rule);
            this.#autoRuleToColumn.set(ruleId, col);
            this.#columnToAutoRule.set(col, ruleId);
            this.#columnTypeManager.markBridgeTaken(col);
        }
    }

    /**
     * 获取桥接状态信息
     */
    getBridgeStatus(): {
        active: boolean;
        autoRuleCount: number;
        bridgedColumnCount: number;
        details: Array<{ col: number; ruleId: string | null; columnType: string; hasValidation: boolean }>;
    } {
        const details: Array<{ col: number; ruleId: string | null; columnType: string; hasValidation: boolean }> = [];
        for (const [col] of this.#columnTypeManager.columnsConfig) {
            const config = this.#columnTypeManager.getColumnConfig(col);
            details.push({
                col,
                ruleId: this.#columnToAutoRule.get(col) || null,
                columnType: this.#columnTypeManager.getColumnType(col),
                hasValidation: !!config?.validation,
            });
        }
        return {
            active: this.#active,
            autoRuleCount: this.#autoRuleToColumn.size,
            bridgedColumnCount: this.#columnToAutoRule.size,
            details,
        };
    }

    hasAutoRuleForColumn(col: number): boolean {
        return this.#columnToAutoRule.has(col);
    }

    getAutoRuleIdForColumn(col: number): string | null {
        return this.#columnToAutoRule.get(col) || null;
    }

    // ── 私有方法 ──

    /**
     * 从 validation 子对象创建 ValidationRule（直传模式）
     */
    #createRuleFromValidation(col: number, config: Record<string, any>): ValidationRule | null {
        const v = config.validation;
        const columnType = config.type as string;

        const inferredType = v.type || this.#inferValidationType(columnType, config);
        const inferredRange = v.range || this.#colToRange(col);
        const inferredPriority = v.priority ?? AUTO_RULE_PRIORITY;
        const inferredErrorStyle = v.errorStyle || this.#defaultErrorStyle;

        if (!inferredType) return null;

        const ruleConfig: Record<string, any> = {
            range: inferredRange,
            type: inferredType,
            priority: inferredPriority,
            errorStyle: inferredErrorStyle,
            allowBlank: v.allowBlank ?? true,
            showDropdown: v.showDropdown ?? true,
            showErrorMessage: v.showErrorMessage ?? true,
            errorTitle: v.errorTitle || "输入错误",
            inputTitle: v.inputTitle || "提示",
            metadata: {
                source: BRIDGE_SOURCE,
                columnType: columnType,
                column: col,
                generatedAt: Date.now(),
            },
        };

        if (v.operator !== undefined) ruleConfig.operator = v.operator;
        if (v.value !== undefined) ruleConfig.value = v.value;
        if (v.source !== undefined) ruleConfig.source = v.source;
        if (v.formula !== undefined) ruleConfig.formula = v.formula;
        if (v.pattern !== undefined) ruleConfig.pattern = v.pattern;
        if (v.errorMessage !== undefined) ruleConfig.errorMessage = v.errorMessage;
        if (v.inputMessage !== undefined) ruleConfig.inputMessage = v.inputMessage;

        return new ValidationRule(ruleConfig);
    }

    /**
     * 从列类型 + options 推断 ValidationRule（向后兼容）
     */
    #createRuleFromColumnType(col: number, config: Record<string, any>): ValidationRule | null {
        const typeName = config.type as string;
        const options = config.options || {};
        const range = this.#colToRange(col);

        switch (typeName) {
            case "numeric":
                return this.#inferNumericRule(col, range, options);
            case "select":
                return this.#inferSelectRule(col, range, options);
            case "date":
                return this.#inferDateRule(col, range, options);
            case "text":
            case "textarea":
                return this.#inferTextRule(col, range, options);
            default:
                return null;
        }
    }

    /**
     * 从列类型推断验证类型
     */
    #inferValidationType(columnType: string, config: Record<string, any>): string | null {
        switch (columnType) {
            case "numeric":
                return "number";
            case "select":
                return "list";
            case "date": {
                const pattern = config.options?.dateFormat?.pattern || "YYYY-MM-DD";
                if (/^[Hhms: ]+$/.test(pattern)) return "time";
                if (/[Hhms]/.test(pattern)) return "datetime";
                return "date";
            }
            case "text":
            case "textarea":
                return "text";
            default:
                return null;
        }
    }

    #inferNumericRule(col: number, range: string, options: Record<string, any>): ValidationRule | null {
        const hasMin = options.min !== undefined && options.min !== null;
        const hasMax = options.max !== undefined && options.max !== null;
        if (!hasMin && !hasMax) return null;

        let operator: string, value: any, errorMessage: string;
        if (hasMin && hasMax) {
            operator = "between";
            value = [options.min, options.max];
            errorMessage = `数值必须在 ${options.min} 到 ${options.max} 之间`;
        } else if (hasMin) {
            operator = "greaterThanOrEqual";
            value = options.min;
            errorMessage = `数值不能小于 ${options.min}`;
        } else {
            operator = "lessThanOrEqual";
            value = options.max;
            errorMessage = `数值不能大于 ${options.max}`;
        }

        return new ValidationRule({
            range,
            type: "number",
            operator,
            value,
            errorMessage,
            errorStyle: this.#defaultErrorStyle,
            priority: AUTO_RULE_PRIORITY,
            metadata: { source: BRIDGE_SOURCE, columnType: "numeric", column: col, generatedAt: Date.now() },
        });
    }

    #inferSelectRule(col: number, range: string, options: Record<string, any>): ValidationRule | null {
        const source = options.source;
        if (!Array.isArray(source) || source.length === 0) return null;

        let validValues: any[];
        if (typeof source[0] === "object" && source[0] !== null && "value" in source[0]) {
            validValues = source.map((item: any) => item.value).filter((v: any) => v !== undefined && v !== null);
        } else {
            validValues = [...source];
        }
        if (validValues.length === 0) return null;

        return new ValidationRule({
            range,
            type: "list",
            source: validValues,
            showDropdown: true,
            errorMessage: "请从下拉列表中选择有效选项",
            errorStyle: this.#defaultErrorStyle,
            priority: AUTO_RULE_PRIORITY,
            metadata: { source: BRIDGE_SOURCE, columnType: "select", column: col, generatedAt: Date.now() },
        });
    }

    #inferDateRule(col: number, range: string, options: Record<string, any>): ValidationRule | null {
        const hasMin = options.min !== undefined && options.min !== null;
        const hasMax = options.max !== undefined && options.max !== null;
        if (!hasMin && !hasMax) return null;

        const pattern = options.dateFormat?.pattern || "YYYY-MM-DD";
        const isTimeOnly = /^[Hhms: ]+$/.test(pattern);
        const validationType = isTimeOnly ? "time" : "date";
        const label = isTimeOnly ? "时间" : "日期";

        let operator: string, value: any, errorMessage: string;
        if (hasMin && hasMax) {
            operator = "between";
            value = [options.min, options.max];
            errorMessage = `${label}必须在 ${options.min} 到 ${options.max} 之间`;
        } else if (hasMin) {
            operator = "greaterThanOrEqual";
            value = options.min;
            errorMessage = `${label}不能早于 ${options.min}`;
        } else {
            operator = "lessThanOrEqual";
            value = options.max;
            errorMessage = `${label}不能晚于 ${options.max}`;
        }

        return new ValidationRule({
            range,
            type: validationType,
            operator,
            value,
            errorMessage,
            errorStyle: this.#defaultErrorStyle,
            priority: AUTO_RULE_PRIORITY,
            metadata: { source: BRIDGE_SOURCE, columnType: "date", column: col, generatedAt: Date.now() },
        });
    }

    #inferTextRule(col: number, range: string, options: Record<string, any>): ValidationRule | null {
        const maxLength = options.maxLength;
        if (maxLength === undefined || maxLength === null) return null;

        return new ValidationRule({
            range,
            type: "text",
            operator: "lessThanOrEqual",
            value: maxLength,
            errorMessage: `文本长度不能超过 ${maxLength} 个字符`,
            errorStyle: this.#defaultErrorStyle,
            priority: AUTO_RULE_PRIORITY,
            metadata: { source: BRIDGE_SOURCE, columnType: "text", column: col, generatedAt: Date.now() },
        });
    }

    /**
     * 检查列配置 options 中是否有可桥接约束（向后兼容）
     */
    #hasBridgeableConstraint(config: Record<string, any>): boolean {
        const typeName = config.type as string;
        const options = config.options || {};
        switch (typeName) {
            case "numeric":
                return options.min !== undefined || options.max !== undefined;
            case "select":
                return Array.isArray(options.source) && options.source.length > 0;
            case "date":
                return options.min !== undefined || options.max !== undefined;
            case "text":
            case "textarea":
                return options.maxLength !== undefined;
            default:
                return false;
        }
    }

    /**
     * 检查指定列是否已存在手动同类验证规则
     */
    #hasManualRuleForColumn(col: number, validationType: string): boolean {
        const rules = this.#validationEngine.getRulesForCell(0, col);
        return rules.some((rule: any) => rule.type === validationType && rule.metadata?.source !== BRIDGE_SOURCE);
    }

    /**
     * 移除指定列的自动规则 + 取消接管标记
     */
    #removeAutoRuleForColumn(col: number): void {
        const existingRuleId = this.#columnToAutoRule.get(col);
        if (existingRuleId) {
            this.#validationEngine.removeRule(existingRuleId);
            this.#autoRuleToColumn.delete(existingRuleId);
            this.#columnToAutoRule.delete(col);
        }
        this.#columnTypeManager.unmarkBridgeTaken(col);
    }

    /**
     * 列号 → 整列范围字符串
     */
    #colToRange(col: number): string {
        const colLetter = indexToCol(col);
        return `${colLetter}:${colLetter}`;
    }

    /**
     * 提取 validation 快照（用于增量同步对比）
     */
    #extractValidationSnapshot(config: Record<string, any>): Record<string, any> {
        if (config.validation) {
            return { validation: { ...config.validation } };
        }
        const options = config.options || {};
        const typeName = config.type as string;
        switch (typeName) {
            case "numeric":
                return { type: typeName, min: options.min, max: options.max };
            case "select":
                return { type: typeName, source: options.source ? [...options.source] : null };
            case "date":
                return { type: typeName, min: options.min, max: options.max, pattern: options.dateFormat?.pattern };
            case "text":
            case "textarea":
                return { type: typeName, maxLength: options.maxLength };
            default:
                return { type: typeName };
        }
    }

    /**
     * 快照深度比较
     */
    #snapshotEqual(a: Record<string, any> | null, b: Record<string, any> | null): boolean {
        if (a === null && b === null) return true;
        if (a === null || b === null) return false;
        const keysA = Object.keys(a);
        const keysB = Object.keys(b);
        if (keysA.length !== keysB.length) return false;
        for (const key of keysA) {
            const va = a[key];
            const vb = b[key];
            if (va && typeof va === "object" && vb && typeof vb === "object") {
                if (!this.#snapshotEqual(va, vb)) return false;
            } else if (Array.isArray(va) && Array.isArray(vb)) {
                if (va.length !== vb.length || !va.every((v: any, i: number) => v === vb[i])) return false;
            } else if (va !== vb) {
                return false;
            }
        }
        return true;
    }
}
