/**
 * 错误级别与错误码常量定义
 *
 * ERROR_LEVEL: 错误严重程度分级（0-4）
 * ERROR_CODE: 全局错误码字符串常量，用于统一错误标识
 */
export interface ErrorLevel {
    readonly DEBUG: 0;
    readonly INFO: 1;
    readonly WARN: 2;
    readonly ERROR: 3;
    readonly FATAL: 4;
}

export const ERROR_LEVEL: ErrorLevel = Object.freeze({
    DEBUG: 0,
    INFO: 1,
    WARN: 2,
    ERROR: 3,
    FATAL: 4,
});

export interface ErrorCode {
    // ── 插件 ──
    readonly PLUGIN_NOT_REGISTERED: "PLUGIN_NOT_REGISTERED";
    readonly PLUGIN_ALREADY_LOADED: "PLUGIN_ALREADY_LOADED";
    readonly PLUGIN_INVALID_CLASS: "PLUGIN_INVALID_CLASS";
    readonly PLUGIN_ABSTRACT_METHOD: "PLUGIN_ABSTRACT_METHOD";

    // ── 钩子 ──
    readonly HOOK_CALLBACK_INVALID: "HOOK_CALLBACK_INVALID";
    readonly HOOK_EXECUTION_ERROR: "HOOK_EXECUTION_ERROR";

    // ── 类型 ──
    readonly TYPE_NOT_REGISTERED: "TYPE_NOT_REGISTERED";
    readonly TYPE_INVALID_INSTANCE: "TYPE_INVALID_INSTANCE";
    readonly TYPE_PARSE_ERROR: "TYPE_PARSE_ERROR";
    readonly TYPE_INVALID_NAME: "TYPE_INVALID_NAME";
    readonly TYPE_INVALID_CLASS: "TYPE_INVALID_CLASS";
    readonly TYPE_DUPLICATE: "TYPE_DUPLICATE";
    readonly TYPE_INSTANTIATION_ERROR: "TYPE_INSTANTIATION_ERROR";

    // ── 剪贴板 ──
    readonly CLIPBOARD_READ_ERROR: "CLIPBOARD_READ_ERROR";
    readonly CLIPBOARD_WRITE_ERROR: "CLIPBOARD_WRITE_ERROR";
    readonly CLIPBOARD_TYPE_MISMATCH: "CLIPBOARD_TYPE_MISMATCH";

    // ── 数据 ──
    readonly CELL_INVALID_DATA: "CELL_INVALID_DATA";
    readonly INDEX_OUT_OF_BOUNDS: "INDEX_OUT_OF_BOUNDS";

    // ── 渲染 ──
    readonly RENDER_ERROR: "RENDER_ERROR";

    // ── 图层合成器 ──
    readonly LAYER_INVALID_INSTANCE: "LAYER_INVALID_INSTANCE";
    readonly LAYER_ALREADY_REGISTERED: "LAYER_ALREADY_REGISTERED";
    readonly LAYER_RENDER_ERROR: "LAYER_RENDER_ERROR";

    // ── 公式 ──
    readonly FORMULA_INVALID_FUNCTION_NAME: "FORMULA_INVALID_FUNCTION_NAME";
    readonly FORMULA_INVALID_FUNCTION: "FORMULA_INVALID_FUNCTION";
    readonly FORMULA_FUNCTION_OVERRIDE: "FORMULA_FUNCTION_OVERRIDE";
    readonly FORMULA_FUNCTION_NOT_FOUND: "FORMULA_FUNCTION_NOT_FOUND";
    readonly FORMULA_PARSE_ERROR: "FORMULA_PARSE_ERROR";
    readonly FORMULA_EVAL_ERROR: "FORMULA_EVAL_ERROR";
    readonly FORMULA_CIRCULAR_REFERENCE: "FORMULA_CIRCULAR_REFERENCE";
    readonly FORMULA_ARGUMENT_COUNT_INVALID: "FORMULA_ARGUMENT_COUNT_INVALID";

    // ── 搜索 ──
    readonly SEARCH_EMPTY_RANGE: "SEARCH_EMPTY_RANGE";
    readonly SEARCH_EXECUTION_ERROR: "SEARCH_EXECUTION_ERROR";
    readonly SEARCH_INVALID_REGEX: "SEARCH_INVALID_REGEX";
    readonly SEARCH_REPLACE_ERROR: "SEARCH_REPLACE_ERROR";
    readonly SEARCH_REPLACE_ALL_ERROR: "SEARCH_REPLACE_ALL_ERROR";
    readonly SEARCH_CELLS_SKIPPED: "SEARCH_CELLS_SKIPPED";
    readonly SEARCH_HIGHLIGHT_RENDER_ERROR: "SEARCH_HIGHLIGHT_RENDER_ERROR";
    readonly SEARCH_VISIBLE_RANGE_ERROR: "SEARCH_VISIBLE_RANGE_ERROR";
    readonly SEARCH_SCROLL_TO_CELL_ERROR: "SEARCH_SCROLL_TO_CELL_ERROR";
    readonly SEARCH_SELECTION_SYNC_ERROR: "SEARCH_SELECTION_SYNC_ERROR";
    readonly SEARCH_KEYBOARD_EVENT_ERROR: "SEARCH_KEYBOARD_EVENT_ERROR";
    readonly SEARCH_MISSING_CONTEXT: "SEARCH_MISSING_CONTEXT";
    readonly SEARCH_RESULTS_TRUNCATED: "SEARCH_RESULTS_TRUNCATED";
    readonly SEARCH_CELL_SEARCH_ERROR: "SEARCH_CELL_SEARCH_ERROR";
    readonly SEARCH_UI_POPUP_UNREGISTER_ERROR: "SEARCH_UI_POPUP_UNREGISTER_ERROR";
    readonly SEARCH_UI_POSITION_ERROR: "SEARCH_UI_POSITION_ERROR";
    readonly SEARCH_UI_NAVIGATION_ERROR: "SEARCH_UI_NAVIGATION_ERROR";
    readonly SEARCH_UI_CLOSE_ERROR: "SEARCH_UI_CLOSE_ERROR";
    readonly SEARCH_DROPDOWN_SHOW_ERROR: "SEARCH_DROPDOWN_SHOW_ERROR";
    readonly SEARCH_DROPDOWN_WARNING: "SEARCH_DROPDOWN_WARNING";
    readonly SEARCH_NO_RESULTS: "SEARCH_NO_RESULTS";
    readonly SEARCH_REPLACE_ALL_SKIPPED: "SEARCH_REPLACE_ALL_SKIPPED";

    // ── 筛选 ──
    readonly FILTER_UI_POPUP_UNREGISTER_ERROR: "FILTER_UI_POPUP_UNREGISTER_ERROR";
    readonly FILTER_UI_OPEN_ERROR: "FILTER_UI_OPEN_ERROR";
    readonly FILTER_UI_CLOSE_ERROR: "FILTER_UI_CLOSE_ERROR";
    readonly FILTER_UI_APPLY_ERROR: "FILTER_UI_APPLY_ERROR";
    readonly FILTER_UI_CLEAR_ERROR: "FILTER_UI_CLEAR_ERROR";
    readonly FILTER_DROPDOWN_RENDER_ERROR: "FILTER_DROPDOWN_RENDER_ERROR";
    readonly FILTER_DROPDOWN_APPLY_ERROR: "FILTER_DROPDOWN_APPLY_ERROR";
    readonly FILTER_VIRTUAL_LIST_RENDER_ERROR: "FILTER_VIRTUAL_LIST_RENDER_ERROR";

    // ── 排序 ──
    readonly SORT_ENGINE_NOT_INITIALIZED: "SORT_ENGINE_NOT_INITIALIZED";

    // ── 通用 ──
    readonly UNKNOWN: "UNKNOWN";

    // ── 数据验证 ──
    readonly VALIDATION_ERROR: "VALIDATION_ERROR";
    readonly VALIDATOR_NOT_REGISTERED: "VALIDATOR_NOT_REGISTERED";
    readonly VALIDATION_RULE_INVALID: "VALIDATION_RULE_INVALID";
    readonly FORMULA_EVALUATION_ERROR: "FORMULA_EVALUATION_ERROR";
    readonly REGEX_EXECUTION_ERROR: "REGEX_EXECUTION_ERROR";
    readonly LIST_VALIDATION_NOT_IMPLEMENTED: "LIST_VALIDATION_NOT_IMPLEMENTED";
    readonly CONDITIONAL_FORMAT_NOT_INITIALIZED: "CONDITIONAL_FORMAT_NOT_INITIALIZED";
    readonly FORMAT_TEMPLATE_NOT_FOUND: "FORMAT_TEMPLATE_NOT_FOUND";
    readonly FORMAT_APPLY_ERROR: "FORMAT_APPLY_ERROR";
    readonly FORMAT_REMOVE_ERROR: "FORMAT_REMOVE_ERROR";
    readonly FORMULA_ENGINE_INTERFACE_MISSING: "FORMULA_ENGINE_INTERFACE_MISSING";
    readonly VALIDATION_DEBUG_LOG: "VALIDATION_DEBUG_LOG";
    readonly VALIDATION_INFO: "VALIDATION_INFO";

    // ── 导出 ──
    readonly EXPORT_STYLE_FETCH_FAILED: "EXPORT_STYLE_FETCH_FAILED";
    readonly EXPORT_COLOR_PARSE_FAILED: "EXPORT_COLOR_PARSE_FAILED";
    readonly EXPORT_MERGE_ERROR: "EXPORT_MERGE_ERROR";
    readonly EXPORT_DATA_WRITE_ERROR: "EXPORT_DATA_WRITE_ERROR";
    readonly EXPORT_FILE_GENERATE_FAILED: "EXPORT_FILE_GENERATE_FAILED";

    // ── 导入 ──
    readonly IMPORT_FILE_READ_ERROR: "IMPORT_FILE_READ_ERROR";
    readonly IMPORT_FILE_PARSE_ERROR: "IMPORT_FILE_PARSE_ERROR";
    readonly IMPORT_UNSUPPORTED_FORMAT: "IMPORT_UNSUPPORTED_FORMAT";
    readonly IMPORT_DATA_VALIDATION_ERROR: "IMPORT_DATA_VALIDATION_ERROR";
    readonly IMPORT_STYLE_CONVERSION_ERROR: "IMPORT_STYLE_CONVERSION_ERROR";
    readonly IMPORT_CANCELLED_BY_USER: "IMPORT_CANCELLED_BY_USER";
    readonly IMPORT_UNKNOWN_ERROR: "IMPORT_UNKNOWN_ERROR";
    readonly INVALID_FILE_FORMAT: "INVALID_FILE_FORMAT";
    readonly IMPORT_MERGE_WARNING: "IMPORT_MERGE_WARNING";
    readonly IMPORT_DIMENSION_WARNING: "IMPORT_DIMENSION_WARNING";
    readonly IMPORT_RANGE_PARSE_ERROR: "IMPORT_RANGE_PARSE_ERROR";

    // ── 图表 ──
    readonly CHART_CACHE_REBUILD_FAILED: "CHART_CACHE_REBUILD_FAILED";
    readonly CHART_VIEWPORT_TRANSFORM_FAILED: "CHART_VIEWPORT_TRANSFORM_FAILED";
    readonly CHART_RENDER_ERROR: "CHART_RENDER_ERROR";
    readonly CHART_DATA_EXTRACTOR_INIT_FAILED: "CHART_DATA_EXTRACTOR_INIT_FAILED";
    readonly CHART_CACHE_MANAGER_LISTENER_SETUP_FAILED: "CHART_CACHE_MANAGER_LISTENER_SETUP_FAILED";
    readonly CHART_CACHE_MANAGER_LISTENER_REMOVE_FAILED: "CHART_CACHE_MANAGER_LISTENER_REMOVE_FAILED";
    readonly CHART_CACHE_MANAGER_SHEET_UNAVAILABLE: "CHART_CACHE_MANAGER_SHEET_UNAVAILABLE";
    readonly CHART_STRATEGY_DEBUG: "CHART_STRATEGY_DEBUG";
    readonly CHART_STRATEGY_REGISTERED: "CHART_STRATEGY_REGISTERED";
    readonly CHART_RENDER_START: "CHART_RENDER_START";
    readonly CHART_DATA_EMPTY: "CHART_DATA_EMPTY";
    readonly CHART_TYPE_NOT_FOUND: "CHART_TYPE_NOT_FOUND";
    readonly CHART_INVALID_STRATEGY: "CHART_INVALID_STRATEGY";

    // ── 通用日志 ──
    readonly GENERIC_ERROR: "GENERIC_ERROR";
    readonly GENERIC_WARN: "GENERIC_WARN";
    readonly DEBUG_LOG: "DEBUG_LOG";

    // ── 主题 ──
    readonly THEME_STORAGE_LOAD_FAILED: "THEME_STORAGE_LOAD_FAILED";
    readonly THEME_STORAGE_SAVE_FAILED: "THEME_STORAGE_SAVE_FAILED";
    readonly THEME_CONFIG_INVALID_TYPE: "THEME_CONFIG_INVALID_TYPE";
    readonly THEME_CONFIG_MISSING_CONFIG: "THEME_CONFIG_MISSING_CONFIG";
    readonly THEME_CONFIG_MISSING_CELL: "THEME_CONFIG_MISSING_CELL";
    readonly THEME_NOT_FOUND: "THEME_NOT_FOUND";
    readonly THEME_ALREADY_EXISTS: "THEME_ALREADY_EXISTS";
    readonly THEME_CANNOT_REMOVE_ACTIVE: "THEME_CANNOT_REMOVE_ACTIVE";
}

export const ERROR_CODE: ErrorCode = Object.freeze({
    PLUGIN_NOT_REGISTERED: "PLUGIN_NOT_REGISTERED",
    PLUGIN_ALREADY_LOADED: "PLUGIN_ALREADY_LOADED",
    PLUGIN_INVALID_CLASS: "PLUGIN_INVALID_CLASS",
    PLUGIN_ABSTRACT_METHOD: "PLUGIN_ABSTRACT_METHOD",

    HOOK_CALLBACK_INVALID: "HOOK_CALLBACK_INVALID",
    HOOK_EXECUTION_ERROR: "HOOK_EXECUTION_ERROR",

    TYPE_NOT_REGISTERED: "TYPE_NOT_REGISTERED",
    TYPE_INVALID_INSTANCE: "TYPE_INVALID_INSTANCE",
    TYPE_PARSE_ERROR: "TYPE_PARSE_ERROR",
    TYPE_INVALID_NAME: "TYPE_INVALID_NAME",
    TYPE_INVALID_CLASS: "TYPE_INVALID_CLASS",
    TYPE_DUPLICATE: "TYPE_DUPLICATE",
    TYPE_INSTANTIATION_ERROR: "TYPE_INSTANTIATION_ERROR",

    CLIPBOARD_READ_ERROR: "CLIPBOARD_READ_ERROR",
    CLIPBOARD_WRITE_ERROR: "CLIPBOARD_WRITE_ERROR",
    CLIPBOARD_TYPE_MISMATCH: "CLIPBOARD_TYPE_MISMATCH",

    CELL_INVALID_DATA: "CELL_INVALID_DATA",
    INDEX_OUT_OF_BOUNDS: "INDEX_OUT_OF_BOUNDS",

    RENDER_ERROR: "RENDER_ERROR",

    LAYER_INVALID_INSTANCE: "LAYER_INVALID_INSTANCE",
    LAYER_ALREADY_REGISTERED: "LAYER_ALREADY_REGISTERED",
    LAYER_RENDER_ERROR: "LAYER_RENDER_ERROR",

    FORMULA_INVALID_FUNCTION_NAME: "FORMULA_INVALID_FUNCTION_NAME",
    FORMULA_INVALID_FUNCTION: "FORMULA_INVALID_FUNCTION",
    FORMULA_FUNCTION_OVERRIDE: "FORMULA_FUNCTION_OVERRIDE",
    FORMULA_FUNCTION_NOT_FOUND: "FORMULA_FUNCTION_NOT_FOUND",
    FORMULA_PARSE_ERROR: "FORMULA_PARSE_ERROR",
    FORMULA_EVAL_ERROR: "FORMULA_EVAL_ERROR",
    FORMULA_CIRCULAR_REFERENCE: "FORMULA_CIRCULAR_REFERENCE",
    FORMULA_ARGUMENT_COUNT_INVALID: "FORMULA_ARGUMENT_COUNT_INVALID",

    SEARCH_EMPTY_RANGE: "SEARCH_EMPTY_RANGE",
    SEARCH_EXECUTION_ERROR: "SEARCH_EXECUTION_ERROR",
    SEARCH_INVALID_REGEX: "SEARCH_INVALID_REGEX",
    SEARCH_REPLACE_ERROR: "SEARCH_REPLACE_ERROR",
    SEARCH_REPLACE_ALL_ERROR: "SEARCH_REPLACE_ALL_ERROR",
    SEARCH_CELLS_SKIPPED: "SEARCH_CELLS_SKIPPED",
    SEARCH_HIGHLIGHT_RENDER_ERROR: "SEARCH_HIGHLIGHT_RENDER_ERROR",
    SEARCH_VISIBLE_RANGE_ERROR: "SEARCH_VISIBLE_RANGE_ERROR",
    SEARCH_SCROLL_TO_CELL_ERROR: "SEARCH_SCROLL_TO_CELL_ERROR",
    SEARCH_SELECTION_SYNC_ERROR: "SEARCH_SELECTION_SYNC_ERROR",
    SEARCH_KEYBOARD_EVENT_ERROR: "SEARCH_KEYBOARD_EVENT_ERROR",
    SEARCH_MISSING_CONTEXT: "SEARCH_MISSING_CONTEXT",
    SEARCH_RESULTS_TRUNCATED: "SEARCH_RESULTS_TRUNCATED",
    SEARCH_CELL_SEARCH_ERROR: "SEARCH_CELL_SEARCH_ERROR",
    SEARCH_UI_POPUP_UNREGISTER_ERROR: "SEARCH_UI_POPUP_UNREGISTER_ERROR",
    SEARCH_UI_POSITION_ERROR: "SEARCH_UI_POSITION_ERROR",
    SEARCH_UI_NAVIGATION_ERROR: "SEARCH_UI_NAVIGATION_ERROR",
    SEARCH_UI_CLOSE_ERROR: "SEARCH_UI_CLOSE_ERROR",
    SEARCH_DROPDOWN_SHOW_ERROR: "SEARCH_DROPDOWN_SHOW_ERROR",
    SEARCH_DROPDOWN_WARNING: "SEARCH_DROPDOWN_WARNING",
    SEARCH_NO_RESULTS: "SEARCH_NO_RESULTS",
    SEARCH_REPLACE_ALL_SKIPPED: "SEARCH_REPLACE_ALL_SKIPPED",

    FILTER_UI_POPUP_UNREGISTER_ERROR: "FILTER_UI_POPUP_UNREGISTER_ERROR",
    FILTER_UI_OPEN_ERROR: "FILTER_UI_OPEN_ERROR",
    FILTER_UI_CLOSE_ERROR: "FILTER_UI_CLOSE_ERROR",
    FILTER_UI_APPLY_ERROR: "FILTER_UI_APPLY_ERROR",
    FILTER_UI_CLEAR_ERROR: "FILTER_UI_CLEAR_ERROR",
    FILTER_DROPDOWN_RENDER_ERROR: "FILTER_DROPDOWN_RENDER_ERROR",
    FILTER_DROPDOWN_APPLY_ERROR: "FILTER_DROPDOWN_APPLY_ERROR",
    FILTER_VIRTUAL_LIST_RENDER_ERROR: "FILTER_VIRTUAL_LIST_RENDER_ERROR",

    SORT_ENGINE_NOT_INITIALIZED: "SORT_ENGINE_NOT_INITIALIZED",

    UNKNOWN: "UNKNOWN",

    VALIDATION_ERROR: "VALIDATION_ERROR",
    VALIDATOR_NOT_REGISTERED: "VALIDATOR_NOT_REGISTERED",
    VALIDATION_RULE_INVALID: "VALIDATION_RULE_INVALID",
    FORMULA_EVALUATION_ERROR: "FORMULA_EVALUATION_ERROR",
    REGEX_EXECUTION_ERROR: "REGEX_EXECUTION_ERROR",
    LIST_VALIDATION_NOT_IMPLEMENTED: "LIST_VALIDATION_NOT_IMPLEMENTED",
    CONDITIONAL_FORMAT_NOT_INITIALIZED: "CONDITIONAL_FORMAT_NOT_INITIALIZED",
    FORMAT_TEMPLATE_NOT_FOUND: "FORMAT_TEMPLATE_NOT_FOUND",
    FORMAT_APPLY_ERROR: "FORMAT_APPLY_ERROR",
    FORMAT_REMOVE_ERROR: "FORMAT_REMOVE_ERROR",
    FORMULA_ENGINE_INTERFACE_MISSING: "FORMULA_ENGINE_INTERFACE_MISSING",
    VALIDATION_DEBUG_LOG: "VALIDATION_DEBUG_LOG",
    VALIDATION_INFO: "VALIDATION_INFO",

    EXPORT_STYLE_FETCH_FAILED: "EXPORT_STYLE_FETCH_FAILED",
    EXPORT_COLOR_PARSE_FAILED: "EXPORT_COLOR_PARSE_FAILED",
    EXPORT_MERGE_ERROR: "EXPORT_MERGE_ERROR",
    EXPORT_DATA_WRITE_ERROR: "EXPORT_DATA_WRITE_ERROR",
    EXPORT_FILE_GENERATE_FAILED: "EXPORT_FILE_GENERATE_FAILED",

    IMPORT_FILE_READ_ERROR: "IMPORT_FILE_READ_ERROR",
    IMPORT_FILE_PARSE_ERROR: "IMPORT_FILE_PARSE_ERROR",
    IMPORT_UNSUPPORTED_FORMAT: "IMPORT_UNSUPPORTED_FORMAT",
    IMPORT_DATA_VALIDATION_ERROR: "IMPORT_DATA_VALIDATION_ERROR",
    IMPORT_STYLE_CONVERSION_ERROR: "IMPORT_STYLE_CONVERSION_ERROR",
    IMPORT_CANCELLED_BY_USER: "IMPORT_CANCELLED_BY_USER",
    IMPORT_UNKNOWN_ERROR: "IMPORT_UNKNOWN_ERROR",
    INVALID_FILE_FORMAT: "INVALID_FILE_FORMAT",
    IMPORT_MERGE_WARNING: "IMPORT_MERGE_WARNING",
    IMPORT_DIMENSION_WARNING: "IMPORT_DIMENSION_WARNING",
    IMPORT_RANGE_PARSE_ERROR: "IMPORT_RANGE_PARSE_ERROR",

    CHART_CACHE_REBUILD_FAILED: "CHART_CACHE_REBUILD_FAILED",
    CHART_VIEWPORT_TRANSFORM_FAILED: "CHART_VIEWPORT_TRANSFORM_FAILED",
    CHART_RENDER_ERROR: "CHART_RENDER_ERROR",
    CHART_DATA_EXTRACTOR_INIT_FAILED: "CHART_DATA_EXTRACTOR_INIT_FAILED",
    CHART_CACHE_MANAGER_LISTENER_SETUP_FAILED: "CHART_CACHE_MANAGER_LISTENER_SETUP_FAILED",
    CHART_CACHE_MANAGER_LISTENER_REMOVE_FAILED: "CHART_CACHE_MANAGER_LISTENER_REMOVE_FAILED",
    CHART_CACHE_MANAGER_SHEET_UNAVAILABLE: "CHART_CACHE_MANAGER_SHEET_UNAVAILABLE",
    CHART_STRATEGY_DEBUG: "CHART_STRATEGY_DEBUG",
    CHART_STRATEGY_REGISTERED: "CHART_STRATEGY_REGISTERED",
    CHART_RENDER_START: "CHART_RENDER_START",
    CHART_DATA_EMPTY: "CHART_DATA_EMPTY",
    CHART_TYPE_NOT_FOUND: "CHART_TYPE_NOT_FOUND",
    CHART_INVALID_STRATEGY: "CHART_INVALID_STRATEGY",

    GENERIC_ERROR: "GENERIC_ERROR",
    GENERIC_WARN: "GENERIC_WARN",
    DEBUG_LOG: "DEBUG_LOG",

    THEME_STORAGE_LOAD_FAILED: "THEME_STORAGE_LOAD_FAILED",
    THEME_STORAGE_SAVE_FAILED: "THEME_STORAGE_SAVE_FAILED",
    THEME_CONFIG_INVALID_TYPE: "THEME_CONFIG_INVALID_TYPE",
    THEME_CONFIG_MISSING_CONFIG: "THEME_CONFIG_MISSING_CONFIG",
    THEME_CONFIG_MISSING_CELL: "THEME_CONFIG_MISSING_CELL",
    THEME_NOT_FOUND: "THEME_NOT_FOUND",
    THEME_ALREADY_EXISTS: "THEME_ALREADY_EXISTS",
    THEME_CANNOT_REMOVE_ACTIVE: "THEME_CANNOT_REMOVE_ACTIVE",
});