/**
 * 默认主题配置
 */
export const defaultThemeConfig = {
    name: "default",
    displayName: "默认主题",
    version: "1.0.0",
    config: {
        cell: {
            default: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#000",
                backgroundColor: "transparent",
                textAlign: "left",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            hyperlink: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#1a73e8",
                backgroundColor: "transparent",
                textAlign: "left",
                verticalAlign: "middle",
                textDecoration: "underline",
                cursor: "pointer",
            },
            header: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "bold",
                color: "#fff",
                backgroundColor: "#4CAF50",
                textAlign: "center",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            selected: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#fff",
                backgroundColor: "#1a73e8",
                textAlign: "left",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            numeric: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#333",
                backgroundColor: "transparent",
                textAlign: "right",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            text: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#000",
                backgroundColor: "transparent",
                textAlign: "left",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            textarea: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#000",
                backgroundColor: "transparent",
                textAlign: "left",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            date: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#2E7D32",
                backgroundColor: "transparent",
                textAlign: "center",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            checkbox: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#667eea",
                backgroundColor: "transparent",
                textAlign: "center",
                verticalAlign: "middle",
                textDecoration: "none",
            },
        },
        font: {
            family: "Microsoft YaHei",
            sizes: {
                small: 12,
                medium: 14,
                large: 16,
            },
        },
        colors: {
            primary: "#1a73e8",
            success: "#4CAF50",
            warning: "#ff9800",
            error: "#f44336",
            info: "#2196F3",
        },
    },
};

/**
 * 暗色主题配置
 */
export const darkThemeConfig = {
    name: "dark",
    displayName: "暗色主题",
    version: "1.0.0",
    config: {
        cell: {
            default: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#fff",
                backgroundColor: "#333",
                textAlign: "left",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            hyperlink: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#64B5F6",
                backgroundColor: "#333",
                textAlign: "left",
                verticalAlign: "middle",
                textDecoration: "underline",
                cursor: "pointer",
            },
            header: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "bold",
                color: "#fff",
                backgroundColor: "#2E7D32",
                textAlign: "center",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            selected: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#fff",
                backgroundColor: "#1565C0",
                textAlign: "left",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            numeric: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#ccc",
                backgroundColor: "#333",
                textAlign: "right",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            text: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#fff",
                backgroundColor: "#333",
                textAlign: "left",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            textarea: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#fff",
                backgroundColor: "#333",
                textAlign: "left",
                verticalAlign: "top",
                textDecoration: "none",
            },
            date: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#81C784",
                backgroundColor: "#333",
                textAlign: "center",
                verticalAlign: "middle",
                textDecoration: "none",
            },
            checkbox: {
                fontFamily: "Microsoft YaHei",
                fontSize: 14,
                fontWeight: "normal",
                color: "#667eea",
                backgroundColor: "transparent",
                textAlign: "center",
                verticalAlign: "middle",
                textDecoration: "none",
            },
        },
        font: {
            family: "Microsoft YaHei",
            sizes: {
                small: 12,
                medium: 14,
                large: 16,
            },
        },
        colors: {
            primary: "#64B5F6",
            success: "#66BB6A",
            warning: "#FFA726",
            error: "#EF5350",
            info: "#42A5F5",
        },
    },
};

export const styleTypes = [
    "cell.default",
    "cell.numeric",
    "cell.text",
    "cell.hyperlink",
    "cell.date",
    "cell.checkbox",
    "cell.textarea",
    "cell.header",
    "cell.selected",
];
