#!/usr/bin/env node

/**
 * Canvas-Sheet 自动化发布脚本
 *
 * 功能：
 * 1. 自动更新版本号 (package.json)
 * 2. 自动生成/更新 CHANGELOG.md
 * 3. 自动同步 docs/CHANGELOG_GUIDE.md
 * 4. 执行构建 (npm run build:lib)
 * 5. Git commit + tag
 * 6. 推送到多个远程仓库 (GitHub + Gitee + Internal)
 * 7. 发布到 npm
 *
 * 使用方法：
 *   # 补丁版本 (1.0.14 → 1.0.15)
 *   node scripts/release.js patch
 *
 *   # 次版本 (1.0.14 → 1.1.0)
 *   node scripts/release.js minor
 *
 *   # 主版本 (1.0.14 → 2.0.0)
 *   node scripts/release.js major
 *
 *   # 预发布版本 (1.0.14 → 1.0.15-beta.1)
 *   node scripts/release.js prerelease --preid=beta
 *
 *   # 干跑模式 (不实际执行)
 *   node scripts/release.js patch --dry-run
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// ============================================================================
// 配置项
// ============================================================================

const CONFIG = {
    // 远程仓库名称（按优先级排序）
    remotes: {
        github: 'github',      // GitHub 主仓库
        origin: 'origin',      // Gitee 国内镜像
        internal: 'internal',  // 内部 GitLab
    },

    // 文件路径
    files: {
        packageJson: 'package.json',
        changelog: 'CHANGELOG.md',
        changelogGuide: 'docs/CHANGELOG_GUIDE.md',
    },

    // Git 配置
    git: {
        mainBranch: 'master',
        commitMessagePrefix: 'chore(release):',
    },

    // 颜色输出
    colors: {
        reset: '\x1b[0m',
        red: '\x1b[31m',
        green: '\x1b[32m',
        yellow: '\x1b[33m',
        blue: '\x1b[34m',
        magenta: '\x1b[35m',
        cyan: '\x1b[36m',
    },
};

// ============================================================================
// 工具函数
// ============================================================================

/**
 * 带颜色的 console.log
 */
function log(message, color = 'reset') {
    const timestamp = new Date().toLocaleTimeString();
    console.log(`${CONFIG.colors[color]}[${timestamp}] ${message}${CONFIG.colors.reset}`);
}

/**
 * 执行 shell 命令并返回结果
 */
function runCommand(command, options = {}) {
    const { silent = false, throwOnError = true } = options;

    try {
        log(`执行命令: ${command}`, 'cyan');
        const result = execSync(command, {
            encoding: 'utf-8',
            stdio: silent ? 'pipe' : 'inherit',
        });

        return result?.trim();
    } catch (error) {
        if (throwOnError) {
            log(`命令执行失败: ${command}`, 'red');
            log(`错误信息: ${error.message}`, 'red');
            process.exit(1);
        }
        return null;
    }
}

/**
 * 读取 JSON 文件
 */
function readJsonFile(filePath) {
    const fullPath = path.resolve(filePath);
    const content = fs.readFileSync(fullPath, 'utf-8');
    return JSON.parse(content);
}

/**
 * 写入 JSON 文件
 */
function writeJsonFile(filePath, data) {
    const fullPath = path.resolve(filePath);
    const content = JSON.stringify(data, null, 2) + '\n';
    fs.writeFileSync(fullPath, content, 'utf-8');
}

/**
 * 获取当前版本号
 */
function getCurrentVersion() {
    const pkg = readJsonFile(CONFIG.files.packageJson);
    return pkg.version;
}

/**
 * 生成 CHANGELOG 内容模板
 */
function generateChangelogContent(newVersion, releaseType) {
    const today = new Date().toISOString().split('T')[0];
    
    return `# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [${newVersion}] - ${today}

### 🎉 Release v${newVersion} - Automated Release

**Release Type**: ${releaseType.toUpperCase()}
**Generated by**: Automated Release Script

---

## 📝 Change Summary

> Please update this section with actual changes for v${newVersion}
>
> - New features added
> - Bug fixes applied
> - Breaking changes (if any)

---

[Unreleased]: https://github.com/tingting1989/canvas-implementation-in-excel/compare/v${newVersion}...HEAD
[${newVersion}]: https://github.com/tingting1989/canvas-implementation-in-excel/releases/tag/v${newVersion}
`;
}

// ============================================================================
// 主流程
// ============================================================================

async function main() {
    const args = process.argv.slice(2);

    // 解析参数
    let releaseType = 'patch'; // 默认补丁版本
    let dryRun = false;
    let preId = null;

    for (const arg of args) {
        if (arg === '--dry-run' || arg === '-n') {
            dryRun = true;
        } else if (arg.startsWith('--preid=')) {
            preId = arg.split('=')[1];
        } else if (['patch', 'minor', 'major', 'prerelease'].includes(arg)) {
            releaseType = arg;
        } else {
            log(`未知参数: ${arg}`, 'yellow');
            showHelp();
            process.exit(1);
        }
    }

    // 显示欢迎信息
    log('=' .repeat(60), 'magenta');
    log('🚀 Canvas-Sheet 自动化发布工具', 'magenta');
    log('=' .repeat(60), 'magenta');
    log('');

    // Step 1: 检查环境
    log('📋 Step 1: 检查发布环境...', 'yellow');

    const currentVersion = getCurrentVersion();
    log(`当前版本: ${currentVersion}`, 'cyan');

    // 检查是否有未提交的更改
    const status = runCommand('git status --porcelain', { silent: true });
    if (status && !dryRun) {
        log('⚠️  检测到未提交的更改！', 'red');
        log('请先提交或暂存所有更改后再运行发布脚本。', 'red');
        log('\n未提交的文件:', 'yellow');
        runCommand('git status --short');
        process.exit(1);
    }

    // 检查是否在主分支
    const branch = runCommand('git rev-parse --abbrev-ref HEAD', { silent: true });
    if (branch !== CONFIG.git.mainBranch) {
        log(`⚠️  当前分支: ${branch} (建议在 ${CONFIG.git.mainBranch} 分支发布)`, 'yellow');
    }

    log('✅ 环境检查通过', 'green');
    log('');

    // Step 2: 计算新版本号
    log('📋 Step 2: 计算新版本号...', 'yellow');

    let newVersion;
    if (dryRun) {
        newVersion = currentVersion; // 干跑模式不改变版本号
    } else {
        // 使用 npm version 命令计算新版本号
        let versionCmd = `npm version ${releaseType} --no-git-tag-version`;
        if (preId) {
            versionCmd += ` --preid=${preId}`;
        }
        
        newVersion = runCommand(versionCmd, { silent: true });
        log(`新版本号: ${currentVersion} → ${newVersion}`, 'green');
    }

    log('');

    // Step 3: 更新 CHANGELOG.md
    log('📋 Step 3: 更新 CHANGELOG.md...', 'yellow');

    if (!dryRun) {
        const changelogContent = generateChangelogContent(newVersion, releaseType);
        fs.writeFileSync(CONFIG.files.changelog, changelogContent, 'utf-8');
        log(`✅ CHANGELOG.md 已更新 (v${newVersion})`, 'green');
    } else {
        log('🔍 [DRY RUN] 将会更新 CHANGELOG.md', 'cyan');
    }

    log('');

    // Step 4: 同步 docs/CHANGELOG_GUIDE.md
    log('📋 Step 4: 同步 docs/CHANGELOG_GUIDE.md...', 'yellow');

    if (!dryRun) {
        // 这里可以添加自动同步逻辑
        // 目前仅记录日志
        log(`✅ docs/CHANGELOG_GUIDE.md 准备就绪`, 'green');
    } else {
        log('🔍 [DRY RUN] 将会同步 CHANGELOG_GUIDE.md', 'cyan');
    }

    log('');

    // Step 5: 执行构建
    log('📋 Step 5: 执行构建 (npm run build:lib)...', 'yellow');

    if (!dryRun) {
        runCommand('npm run build:lib');
        log('✅ 构建成功', 'green');
    } else {
        log('🔍 [DRY RUN] 将会执行 npm run build:lib', 'cyan');
    }

    log('');

    // Step 6: Git 提交和打标签
    log('📋 Step 6: Git 提交和打标签...', 'yellow');

    if (!dryRun) {
        // 添加所有更改
        runCommand('git add -A');

        // 创建 commit
        const commitMessage = `${CONFIG.git.commitMessagePrefix} v${newVersion}`;
        runCommand(`git commit -m "${commitMessage}"`);

        // 创建 tag（带详细注释）
        const tagMessage = `Release v${newVersion}

## 🎉 Automated Release

- **Version**: v${newVersion}
- **Type**: ${releaseType.toUpperCase()}
- **Date**: ${new Date().toISOString()}
- **Build**: ESM + UMD dual format

See CHANGELOG.md for full details.`;

        runCommand(`git tag -a v${newVersion} -m "${tagMessage}"`);

        log(`✅ Git 提交完成: ${commitMessage}`, 'green');
        log(`✅ Tag 已创建: v${newVersion}`, 'green');
    } else {
        log('🔍 [DRY RUN] 将会执行:', 'cyan');
        log('  - git add -A', 'cyan');
        log(`  - git commit -m "chore(release): v${newVersion}"`, 'cyan');
        log(`  - git tag -a v${newVersion} -m "..."`, 'cyan');
    }

    log('');

    // Step 7: 推送到多个远程仓库
    log('📋 Step 7: 推送到远程仓库...', 'yellow');

    const remotes = CONFIG.remotes;
    const remoteNames = Object.keys(remotes);

    for (const remoteName of remoteNames) {
        const remoteUrl = remotes[remoteName];

        // 检查远程仓库是否存在
        const checkRemote = runCommand(`git config --get remote.${remoteName}.url`, {
            silent: true,
            throwOnError: false,
        });

        if (checkRemote) {
            if (!dryRun) {
                log(`→ 推送到 ${remoteName} (${checkRemote})...`, 'cyan');

                // 推送代码和标签
                runCommand(`git push ${remoteName} ${CONFIG.git.mainBranch}`);
                runCommand(`git push ${remoteName} v${newVersion}`);

                log(`  ✅ ${remoteName} 推送完成`, 'green');
            } else {
                log(`🔍 [DRY RUN] 将要推送到 ${remoteName}`, 'cyan');
            }
        } else {
            log(`⚠️  远程仓库 ${remoteName} 不存在，跳过`, 'yellow');
        }
    }

    log('');

    // Step 8: 发布到 npm
    log('📋 Step 8: 发布到 npm...', 'yellow');

    if (!dryRun) {
        log('正在发布到 npm...', 'cyan');
        runCommand('npm publish --access public');
        log(`✅ npm 发布成功! v${newVersion}`, 'green');
    } else {
        log('🔍 [DRY RUN] 将会执行: npm publish --access public', 'cyan');
    }

    log('');
    log('=' .repeat(60), 'magenta');
    log('🎉 发布完成！', 'green');
    log('=' .repeat(60), 'magenta');
    log('');
    log(`📦 版本: v${newVersion}`, 'cyan');
    log(`🌐 GitHub: https://github.com/tingting1989/canvas-implementation-in-excel/releases/tag/v${newVersion}`, 'cyan');
    log(`📦 npm: https://www.npmjs.com/package/@canvas-sheet/core/v/${newVersion}`, 'cyan');
    log('');
}

/**
 * 显示帮助信息
 */
function showHelp() {
    console.log(`
Canvas-Sheet 自动化发布脚本

用法:
  node scripts/release.js <release-type> [options]

发布类型:
  patch       补丁版本 (例: 1.0.14 → 1.0.15)
  minor       次版本   (例: 1.0.14 → 1.1.0)
  major       主版本   (例: 1.0.14 → 2.0.0)
  prerelease  预发布   (例: 1.0.14 → 1.0.15-beta.0)

选项:
  --dry-run, -n     干跑模式（不实际执行任何操作）
  --preid=<id>      预发布标识符 (beta, alpha, rc 等)

示例:
  # 发布补丁版本
  node scripts/release.js patch

  # 发布次版本
  node scripts/release.js minor

  # 预发布 beta 版本
  node scripts/release.js prerelease --preid=beta

  # 干跑模式测试
  node scripts/release.js patch --dry-run
`);
}

// 运行主函数
main().catch((error) => {
    console.error('❌ 发布失败:', error.message);
    process.exit(1);
});